spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv1.63c0bf311f7a607b
            clientSecret: 7390100449f61c60aec5090a839ecb9f99a2e091
          google:
            clientId: 700086744673-keplb3hc6ere9uiqddg4aleho4i08g37.apps.googleusercontent.com
            clientSecret: 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

